my_module_configuration:
  path: /mymodule/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\MyModule\Controller\Admin\MyModuleConfigurationController::indexActionForm'
  requirements:
    _locale: en|fr|es


my_module_index:
  path: /mymodule/home
  methods:  [GET]
  defaults:
    _controller: 'PrestaShop\Module\MyModule\Controller\Admin\MyModuleController::indexAction'
  requirements:
    _locale: en|fr|es



my_module_search:
  path: /mymodule/home
  methods:  [POST]
  defaults:
    _controller: 'PrestaShop\Module\MyModule\Controller\Admin\MyModuleController::searchAction'



mymodule_reviews_update:
  path: /mymodule/edit/reviews/{review_id}
  methods: [GET , POST]
  defaults:
    _controller: 'PrestaShop\Module\MyModule\Controller\Admin\MyModuleController::editReview'
  requirements:
    _locale: en|fr|es
    review_id: \d+

mymodule_reviews_delete:
  path: /mymodule/delete/reviews/{review_id}
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\MyModule\Controller\Admin\MyModuleController::deleteReview'
  requirements:
    _locale: en|fr|es
    review_id: \d+



mymodule_reviews_create:
  path: /mymodule/create/reviews/{id_order}/{id_product}/{id_customer}
  methods:  [GET , POST]
  defaults:
    _controller: 'PrestaShop\Module\MyModule\Controller\Admin\MyModuleController::createReview'
  requirements:
    _locale: en|fr|es
    review_id: \d+